"""Turn the reference implementation's key-order tables into `pyproject_fmt_py/rules/_data.py`.

Every recognized table's formatting is, for the most part, a list of key names and a list of the
arrays under it that hold a set. Those lists are data, so they are taken across rather than
retyped, and the predicates that read them are written by hand in `rules/__init__.py`.

    uv run python tools/extract_rules.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Final

REPO = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO.parent / "toml-fmt" / "pyproject-fmt" / "rust" / "src"

#: The tox rules live in a crate of their own, since the standalone `tox.toml` formatter shares
#: them; their names are written here under one prefix.
DEFAULT_SHARED: Final[tuple[tuple[str, Path], ...]] = (
    ("tox", REPO.parent / "toml-fmt" / "tox-rules" / "src" / "lib.rs"),
)

#: `pub const NAME: &[&str] = &[ ... ];` and the `static` form ruff and uv use.
_CONST = re.compile(r"(?:pub )?(?:const|static) ([A-Z_0-9]+): &\[&str\] = &\[(.*?)\];", re.DOTALL)
#: `const NAME: &[(&str, &str)] = &[ ("from", "to"), … ];`, which names one thing as another.
_PAIRS = re.compile(r"(?:pub )?(?:const|static) ([A-Z_0-9]+): &\[\(&str, &str\)\] = &\[(.*?)\];", re.DOTALL)
_ITEM = re.compile(r'"((?:[^"\\]|\\.)*)"')
_LINE_COMMENT = re.compile(r"//[^\n]*")

_HEADER = '''"""The key names each recognized table is written in the order of.

Generated by `tools/extract_rules.py` from the reference implementation; edit that script and run
it again rather than changing this by hand. The predicates that read these lists live in
`pyproject_fmt_py/rules/__init__.py`.
"""

from __future__ import annotations

from typing import Final

'''


def main(argv: list[str] | None = None) -> int:
    """Write the data module and say how much of it came across."""
    args = _parse_args(argv)
    if not args.src.is_dir():
        print(f"no reference sources at {args.src}", file=sys.stderr)
        return 1

    written: list[str] = [_HEADER]
    count = 0
    sources = [(path.stem, path) for path in sorted(args.src.glob("*.rs"))]
    sources += [(name, path) for name, path in DEFAULT_SHARED if path.is_file()]
    for stem, path in sources:
        text = path.read_text(encoding="utf-8")
        constants = _constants(text)
        pairs = _pairs(text)
        if not constants and not pairs:
            continue
        written.append(f"# -- {stem} " + "-" * (96 - len(stem)) + "\n\n")
        for name, values in constants.items():
            written.append(_spelled(f"{stem.upper()}_{name}", values))
            count += 1
        for name, held in pairs.items():
            written.append(_spelled_pairs(f"{stem.upper()}_{name}", held))
            count += 1
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(written), encoding="utf-8")
    print(f"{count} lists written to {args.out}")
    return 0


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", type=Path, default=DEFAULT_SRC, help="the reference's rule modules")
    parser.add_argument("--out", type=Path, default=REPO / "pyproject_fmt_py" / "rules" / "_data.py")
    return parser.parse_args(argv)


def _constants(text: str) -> dict[str, list[str]]:
    found: dict[str, list[str]] = {}
    for name, body in _CONST.findall(text):
        # a name the reference commented out is not one the file writes
        items = _ITEM.findall(_LINE_COMMENT.sub("", body))
        found[name] = [item.encode().decode("unicode_escape") for item in items]
    return found


def _pairs(text: str) -> dict[str, list[tuple[str, str]]]:
    found: dict[str, list[tuple[str, str]]] = {}
    for name, body in _PAIRS.findall(text):
        items = _ITEM.findall(_LINE_COMMENT.sub("", body))
        found[name] = [(items[at], items[at + 1]) for at in range(0, len(items) - 1, 2)]
    return found


def _spelled_pairs(name: str, values: list[tuple[str, str]]) -> str:
    body = "".join(f"    ({json.dumps(held)}, {json.dumps(to)}),\n" for held, to in values)
    return f"{name}: Final[tuple[tuple[str, str], ...]] = (\n{body})\n\n"


def _spelled(name: str, values: list[str]) -> str:
    if not values:
        return f"{name}: Final[tuple[str, ...]] = ()\n\n"
    body = "".join(f"    {json.dumps(value)},\n" for value in values)
    return f"{name}: Final[tuple[str, ...]] = (\n{body})\n\n"


if __name__ == "__main__":
    raise SystemExit(main())
